/**
 * STOP! DO NOT EDIT THIS FILE!
 *
 * This file is a template and should not be modified. When you run the Installer (Installer.app),
 * this file is used to tell the script where to find the application. The tokens are replaced automatically.
 */
#includepath "@IJ2AI_PATH@/lib/jsx-common/";
#include     "@IJ2AI_PATH@/main.jsx";